In [1]:

import numpy as np

X = np.array(([2,9],[1,5],[3,6]), dtype = float)
Y = np.array(([92],[86],[89]), dtype = float)
X = X/np.amax(X,axis=0) 
Y = Y/100

def sigmoid(x):
    return 1/(1 + np.exp(-x))
def derivatives(x):
    return x*(1-x)

epoch = 20
lr=0.1
ini=2
hn=3
on=1

wh = np.random.uniform(size=(ini,hn))
bh=np.random.uniform(size=(1,hn))

wout = np.random.uniform(size=(hn,on))
bout=np.random.uniform(size=(1,on))

for i in range(epoch):
    
    #o/p forward prop
    hinp = np.dot(X,wh) + bh
    hlayer = sigmoid(hinp)
    oinp = np.dot(hlayer,wout) + bout
    output = sigmoid(oinp)
 
    
    
    #error back prop.
    eo = (Y - output)*derivatives(output)
    eh = eo.dot(wout.T)*derivatives(hlayer)
    
    
    
    #LC addition to wts
    wh+=X.T.dot(eh)*lr
    wout+=hlayer.T.dot(eo)*lr
    print("epoch=",i,"lr=",lr,"error=",eh)
    
 
print("Input\n" ,X)
print("Actual Output\n", Y)
print("Predicted Output\n" ,output)


epoch= 0 lr= 0.1 error= [[1.70363677e-06 4.72223892e-03 6.22700642e-04]
 [1.40088055e-06 5.05107413e-03 6.75342130e-04]
 [1.37773631e-06 3.55336148e-03 5.45652212e-04]]
epoch= 1 lr= 0.1 error= [[5.99405968e-05 4.63468363e-03 6.48320135e-04]
 [4.91349920e-05 4.94501060e-03 7.00998788e-04]
 [4.82770511e-05 3.47322678e-03 5.65796827e-04]]
epoch= 2 lr= 0.1 error= [[1.13429832e-04 4.54925861e-03 6.71191691e-04]
 [9.26864220e-05 4.84134374e-03 7.23487586e-04]
 [9.09859323e-05 3.39525587e-03 5.83376680e-04]]
epoch= 3 lr= 0.1 error= [[0.00016257 0.00446596 0.00069157]
 [0.00013241 0.00474008 0.0007431 ]
 [0.00012987 0.00331942 0.00059864]]
epoch= 4 lr= 0.1 error= [[0.00020772 0.00438477 0.00070968]
 [0.00016863 0.00464121 0.00076012]
 [0.00016526 0.0032457  0.00061181]]
epoch= 5 lr= 0.1 error= [[0.00024921 0.00430568 0.00072572]
 [0.00020163 0.00454472 0.00077476]
 [0.00019746 0.00317405 0.00062309]]
epoch= 6 lr= 0.1 error= [[0.00028734 0.00422864 0.0007399 ]
 [0.00023168 0.00445058 0.00078727